### ISSUE TITLE
The run commands in "style_transfer/data_proc/gen_dataset.sh" were annotated

### ISSUE THREAD

**Issue by XanderXu1998** [DeepMotionEditing/deep-motion-editing#100]
The run commands in "_style_transfer/data_proc/gen_dataset.sh_" were annotated, so the step '_sh gen_dataset. Sh_' from **Train from Scratch** in the tutorial did not get the desired result

**Comment by HalfSummer11** [comment]
Hi, thanks for letting us know. `gen_dataset.sh` is now updated.
