### ISSUE TITLE
骨骼卷积是汇聚了3个时刻的关节信息吗？

### ISSUE THREAD

**Issue by zhangcheng828** [DeepMotionEditing/deep-motion-editing#102]
![QQ截图20201102125732](https://user-images.githubusercontent.com/72736693/97831604-80579000-1d0b-11eb-90b3-3cab678868b6.png)

**Comment by PeizhuoLi** [comment]
你好，这里是一个简化的示意图。骨骼卷积在时间轴方向是一个1D卷积。在我们的实现中kernel_size是被设置为15的。
