### ISSUE TITLE
Is it possible to run rendering without GUI?

### ISSUE THREAD

**Issue by xychu** [DeepMotionEditing/deep-motion-editing#105]
Great work and I wonder if  the rendering part could run on Envs that without GUI( like docker container).

**Comment by PeizhuoLi** [comment]
A simple solution is to use Cycles as blender's render backend (by adding a parameter "--render_engine=cycles"). However, this is a ray-tracing engine and is significantly slower than the default rasterization one.

The default render engine eevee is implemented by OpenGL and using OpenGL in a headless system is tricky (particularly it's [not officially supported](https://docs.blender.org/manual/en/latest/render/eevee/limitations.html) by Blender). As I know there might exist some tricks like using EGL to make it happen, but I didn't try them.
