### ISSUE TITLE
你好，请问readme中运动重定向的pretrained_retargeting.pth是什么意思？

### ISSUE THREAD

**Issue by helloyizhengjun** [DeepMotionEditing/deep-motion-editing#106]
前辈你好，请问readme中运动重定向的python test.py -model_path retargeting/models/pretrained_retargeting.pth -input_A retargeting/examples/IS_motion_input -input_B retargeting/examples/IS_skeleton_input -edit_type retargeting这里面的pretrained_retargeting.pth是什么意思？

**Comment by PeizhuoLi** [comment]
你好，请参见我们[最新版](https://github.com/DeepMotionEditing/deep-motion-editing/blob/master/README.md)的readme，你提到的这个版本已经废弃了。

**Comment by helloyizhengjun** [comment]
非常感谢



---原始邮件---
发件人: "Peizhuo"<notifications@github.com&gt;
发送时间: 2020年11月15日(周日) 晚上10:18
收件人: "DeepMotionEditing/deep-motion-editing"<deep-motion-editing@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"helloyizhengjun"<2812099759@qq.com&gt;;
主题: Re: [DeepMotionEditing/deep-motion-editing] 你好，请问readme中运动重定向的pretrained_retargeting.pth是什么意思？ (#106)




 
你好，请参见我们最新版的readme，你提到的这个版本已经废弃了。
