### ISSUE TITLE
运行sh demo.sh出错

### ISSUE THREAD

**Issue by Vincent-2017** [DeepMotionEditing/deep-motion-editing#107]
![image](https://user-images.githubusercontent.com/26915856/100564961-5b037500-32fd-11eb-8991-fcbd02956e59.png)
你好，我运行sh demo.sh报错找不到result.bvh，我看见代码里有
![image](https://user-images.githubusercontent.com/26915856/100565045-900fc780-32fd-11eb-9482-cdc53082e0c5.png)
是什么原因呢，谢谢

**Comment by PeizhuoLi** [comment]
你好，根据你的截图，这里报错找不到result.bvh是因为在运行eval_single_pair.py (demo.py:34行) 时出现了Segmentation fault。由于我也是第一次遇到这个问题，如果你能提供更多eval_single_pair的相关运行信息也许会更有帮助。

**Comment by Vincent-2017** [comment]
是否是因为配置过低导致的，我的GPU是1050ti，显存4GB

**Comment by Vincent-2017** [comment]
我换机器后就没问题了
