### ISSUE TITLE
what‘s the difference between motion retargeting and style transfer？

### ISSUE THREAD

**Issue by sunbin1357** [DeepMotionEditing/deep-motion-editing#108]
what‘s the difference between motion retargeting and style transfer？I think style transfer is also motion retargeting.

**Comment by PeizhuoLi** [comment]
Maybe thread #67 can be helpful.

**Comment by sunbin1357** [comment]
in #67,  you said A and B have the same skeleton for style transfer. Is the same skeleton the same person？
Based on your answer in #67, can I think of the new paper TransMoMo as a combination of motion retargeting and style transfer.
