### ISSUE TITLE
是否尝试过将人的姿态retarget到狗身上

### ISSUE THREAD

**Issue by sunbin1357** [DeepMotionEditing/deep-motion-editing#109]
是否尝试过将人的姿态retarget到狗身上？效果怎么样

**Comment by PeizhuoLi** [comment]
你好，我们目前还没有进行过这样的尝试。在我们的介绍视频中给出了猩猩和狗之间retargeting的例子，由于一些原因效果并不太成功。

**Comment by sunbin1357** [comment]
> 你好，我们目前还没有进行过这样的尝试。在我们的介绍视频中给出了猩猩和狗之间retargeting的例子，由于一些原因效果并不太成功。

效果差的主要原因是什么呢？目前有相关的国内外论文吗？ 我一直没找到。谢谢🙏
