### ISSUE TITLE
将动作retarget自己的人体模型上需要哪些准备？

### ISSUE THREAD

**Issue by Vincent-2017** [DeepMotionEditing/deep-motion-editing#110]
作者你好，目前我retarget的目标是解决相同关节数量，不同骨骼长度的问题，看了paper以及相关问题后，我有以下几个疑问：
1. 我现在有一些自己的人体模型，想验证下你们提供的模型效果，根据我自己的理解，是不是只需要生成人物模型对应的骨骼信息（bvh文件）就行？目前我没有人物模型相关的motion数据，所以bvh文件中motion数据这部分我该怎样处理？
2. 看了类似问题，是否想在特定人物模型上表现比较好就必须重新训练？那训练前需要(1)准备人物模型bvh文件，(2)注意人物模型的Tpose保持为双手两侧展开，与肩同高，除了这两步，还需要其他的准备吗？
3. 人体模型的Tpose调节是只需要基本调整到双手两侧展开，与肩同高就行（视觉上），还是必须从数值上严格保证（比如需要严格平行于某个轴，与某个轴夹角几度这类的要求）？以及Mixamo数据的Tpose是数值严格对齐的还是视觉上对齐到Tpose?
4. 重新训练的难度，我看有些问题说训练调参需要比较多的技巧
希望有空能解答我的疑惑，谢谢。

**Comment by PeizhuoLi** [comment]
你好，解决相同关节数量的retargeting是相对简单的。

1. 由于我们使用了per-character normalization, 需要有每个character的representation对应的均值和方差，所以除开bvh之外，还需要从一些动作中提取统计量。如果实在没有的话，也许也能从给出的数据集中寻找类似的角色的统计量来使用

2. 重新训练还需要有人体模型的动作。

3. T-Pose只需要视觉上类似。Mixamo的数据也是视觉上对齐。

4. 比较困难的部分是不同关节数量的训练中需要用到的对抗网络。相同关节数量的训练比较简单直接。

**Comment by Vincent-2017** [comment]
> 1. 由于我们使用了per-character normalization, 需要有每个character的representation对应的均值和方差，所以除开bvh之外，还需要从一些动作中提取统计量。如果实在没有的话，也许也能从给出的数据集中寻找类似的角色的统计量来使用
多谢回复，我还有点疑问。类似的角色是指骨骼长度与我的人体模型接近的吗？还是指mixamo上角色的骨骼比例与我的人体模型骨骼比例接近？按照我的理解是前者是绝对值，后者是相对值。另外，我看同样的动作在不同角色上面对应的关节转角不同，就是这些角色间做了retargeting是吧，我看有问题讨论了mixamo数据的retarget方法和精度问题，是因为没有其他数据可供选择是吧？
> 4. 比较困难的部分是不同关节数量的训练中需要用到的对抗网络。相同关节数量的训练比较简单直接。
这里的简单直接是指用paired的数据来训练吗，有监督的方式？我看有复现是用paired的数据来做的。

**Comment by PeizhuoLi** [comment]
1. 如果要借用别的角色的统计量，需要全局大小也接近，不然在global position对应的通道统计量差别会很大。使用Mixamo是因为这是我们能找到唯一在inference的时候有ground truth的数据集。

2. 是无监督的训练。

**Comment by Vincent-2017** [comment]
好的，谢谢

**Comment by sunbin1357** [comment]
解决相同关节数量的retargeting有哪些简单的模型啊
