### ISSUE TITLE
在自己的角色上测试出现load模型错误

### ISSUE THREAD

**Issue by Vincent-2017** [DeepMotionEditing/deep-motion-editing#111]
大神你好，我有下面几个疑问：
1. 请问下带有"_m.bvh"后缀的角色有什么作用吗？能否具体解释一下。
2. 我在测试cross_retarget效果的时候发现['Mousey_m', 'Goblin_m', 'Mremireh_m', 'Vampire_m']四个角色都是28个关节的，测试没问题，但我用自己的25关节的角色做测试会出现load模型错误。我在测试前生成了mean和var以及std_bvhs中的角色文件，而且25关节与bvh_parser中的corps_name_2完全一致，我打开了std_bvhs下对应的角色bvh，显示如下图
![Selection_023](https://user-images.githubusercontent.com/26915856/101897565-b713a680-3be5-11eb-9485-541128c777ac.png)
![Selection_024](https://user-images.githubusercontent.com/26915856/101897566-b844d380-3be5-11eb-99da-9176ef5b0e64.png)

。
不太清楚哪个步骤出现了问题

**Comment by PeizhuoLi** [comment]
1. 在论文的6.3节中我们提到了为了增加两种拓扑之间的差距，我们手动将一些关节split成两个，在readme中也提供了对应脚本的位置
`In our original implementation, we manually split three joints for skeletons in group A. If you want to follow our routine, run python datasets/split_joint.py. This step is optional.`

2. 不同关节数量需要重新训练，28关节的模型不能直接用在25关节模型上。当然使用上面提到的split脚本就可以了。

**Comment by Vincent-2017** [comment]
谢谢大神，我使用了split_joints增加了3个关节点之后测试cross_retarget效果还不错。我测试了clap相关动作，手部还是没能很好的合并，我有以下几个疑问：
1. 像这种需要将接触动作从A角色retarget到B角色是否只能通过IK来比较完美的实现？如果不用IK，提供大量的接触动作数据训练，直接基于模型推理，是否能达到IK的效果？
2. 我看代码里解决脚接触问题是用优化器来做的，速度不算很快，是否有更快的IK方案（每帧IK耗时几毫秒级别）？
3. 目前的方案能在线retarget吗，即每次输入一帧数据，如果不能的话，主要瓶颈在哪里？

**Comment by PeizhuoLi** [comment]
1. 直接使用目前的框架应该是不容易的。在现有的数据集中有大量脚和地面的接触，但还是需要后续IK修正，从这方面来看不乐观。Neural State Machine for Character-Scene Interactions对接触的处理很好，但是似乎也是用过IK的。

2. 我们的IK是一个非常naive的一阶方法，由于并不是这个paper的主要贡献，因此我们对这方面的研究也不多。或许有一些二阶方法能更快收敛。

3. 目前的框架下是不行的。我们使用的是时间轴方向的1维卷积，所以输出中的一帧是需要前后好几帧的信息。如果实时性要求很高的话也许你可以尝试使用casual convolution来代替我们用到的convolution。

**Comment by Vincent-2017** [comment]
好的，谢谢解惑
