### ISSUE TITLE
WGAN GP vs LSGAN

### ISSUE THREAD

**Issue by fire** [DeepMotionEditing/deep-motion-editing#116]
I was wondering if the effort to replace LSGAN with WGAN GP is worthy.

The literature says that the Generate loss becomes a useful metric in WGAN GP. That could be useful.

**Comment by PeizhuoLi** [comment]
Hi, we've tried WGAN GP but there was not a significant improvement, at least on Mixamo dataset. Training WGANGP will introduce second-order derivative and there will be a considerable overhead. Personally I feel it is not necessary.

**Comment by fire** [comment]
Thanks.
