### ISSUE TITLE
WET CODE!!!

### ISSUE THREAD

**Issue by jdbodyfelt** [DeepMotionEditing/deep-motion-editing#119]
https://github.com/DeepMotionEditing/deep-motion-editing/blob/36f97fe32cc874b2818c42904e7a117886b7740c/retargeting/datasets/bvh_parser.py#L129

You're repeating yourself from L72

**Comment by PeizhuoLi** [comment]
Oh, thanks for the reminding. L130 is indeed redundant. If you like, you can create a pull request.

**Comment by jdbodyfelt** [comment]
Request submitted.
