### ISSUE TITLE
Positions, NOT Offsets. 

### ISSUE THREAD

**Issue by jdbodyfelt** [DeepMotionEditing/deep-motion-editing#121]
https://github.com/DeepMotionEditing/deep-motion-editing/blob/0efe8831709d15f8a7c58d504b0b4f71d9ee11eb/utils/BVH_mod.py#L130

I have FBX exports to BVH that write the positions, but give [0 0 0] on offsets in the BVH. I'm writing a routine to get offset from position, but in error checking my routine against a "standard" BVH (offset & 3 channel rotation except root's 6 channel), I noticed  in `BVH_mod.py` that positions don't write the actual positions, but the offsets only!

**Comment by jdbodyfelt** [comment]
See here for more...
https://github.com/dabeschte/npybvh

**Comment by PeizhuoLi** [comment]
Hi, this code is a slightly modified version of [this](http://theorangeduck.com/page/deep-learning-framework-character-motion-synthesis-and-editing). I think L130 is a simple initialization. If there are position channels it should be filled in L160.

Our code doesn't require position channel, the "standard" BVH should work.
