### ISSUE TITLE
可以给一个Mixamo数据集的百度网盘地址吗？

### ISSUE THREAD

**Issue by TwTravel** [DeepMotionEditing/deep-motion-editing#122]
按照说明把脚本贴到chrome浏览器中，自动下载不来，含泪跪求下好的童鞋分享一下Mixamo数据的train data

**Comment by PeizhuoLi** [comment]
我们在README里面已经提供了预处理好的Mixamo数据集，在[这里](https://pan.baidu.com/s/1PM0maLNCJxBsR9RIv18cTA) (4rgv)
