### ISSUE TITLE
Training Custom Dataset

### ISSUE THREAD

**Issue by DerpyMan101** [DeepMotionEditing/deep-motion-editing#125]
In the Mixamo dataset that you used, there are 8 characters, with 107 corresponding animations for each. I would like to train the network to learn between just two characters. Would you think a dataset with just two characters and 107 corresponding animations would train well? or would more animations need to be added?

**Comment by PeizhuoLi** [comment]
If the animation is diverse enough, I'd say it could be okay.

**Comment by DerpyMan101** [comment]
Also, does the amount of animations for each of the two skeletons have to be the same amount for training?

**Comment by PeizhuoLi** [comment]
It's not necessary. But I was too lazy and I simply use the the minimal length of sequence of all characters (see [here](https://github.com/DeepMotionEditing/deep-motion-editing/blob/0efe8831709d15f8a7c58d504b0b4f71d9ee11eb/retargeting/datasets/combined_motion.py#L84)) so some sequences are ignored. You might want to modify some related code to make it work better with your setting.

**Comment by DerpyMan101** [comment]
Whenever I run preprocess.py, I get this error:

`  File "preprocess.py", line 4, in <module>
    from datasets.bvh_parser import BVH_file
ModuleNotFoundError: No module named 'datasets'`

Would this be because I am using windows?

**Comment by DerpyMan101** [comment]
I am now running on Linux and still have the same problem.
