### ISSUE TITLE
6D Rotational basis instead of Quaternion

### ISSUE THREAD

**Issue by fire** [DeepMotionEditing/deep-motion-editing#126]
Do you think it's worth it to replace the Quaternion implementation with the 6D rot from https://arxiv.org/pdf/1812.07035.pdf?

A basis is a 3x3 matrix.
The basis is normalized.
x_raw is the X Axis / first row of the basis
y_raw is the Y Axis / second row of the basis.
```c++
// On the Continuity of Rotation Representations in Neural Networks
// arXiv:1812.07035
    Basis compute_rotation_matrix_from_ortho_6d(Vector3 x_raw, Vector3 y_raw) {
        Vector3 x = x_raw.normalized();
        Vector3 z = x.cross(y_raw);
        z = z.normalized();
        Vector3 y = z.cross(x);
        Basis basis;
        basis.set_axis(Vector3::AXIS_X, x);
        basis.set_axis(Vector3::AXIS_Y, y);
        basis.set_axis(Vector3::AXIS_Z, z);
        return basis;
    }
```

The result is a 3x3 matrix describing orientation.

![image](https://user-images.githubusercontent.com/32321/104693804-1ec68100-56bf-11eb-8abe-4386c747b08f.png)

**Comment by HalfSummer11** [comment]
I think it's definitely a good idea to try! From my experience, I used this 6D representation as the goal for rotation regression in another project (not for human motion, though), and it did bring a significant improvement.

**Comment by fire** [comment]
Thanks.
