### ISSUE TITLE
Runtime Error while training: "Sizes of tensors must match"

### ISSUE THREAD

**Issue by rainer7** [DeepMotionEditing/deep-motion-editing#129]
Hi guys, first of, thanks for this great paper and repository!
I'm trying to train from scratch with newly downloaded Mixamo characters. Preprocessing and anything before the actual training worked fine. But now when I try to run `python train.py --save_dir = ./training/` I get following Runtime Error:

```
(base) PS C:\MA-stuff\deep-motion-editing-master\retargeting> python train.py --save_dir=./training/

load from file ./datasets/MixamoCustom/Timmy_Superhero.npy
Window count: 84, total frame (without downsampling): 13663
load from file ./datasets/MixamoCustom/Orzit_Fantasy.npy
Window count: 52, total frame (without downsampling): 11003
load from file ./datasets/MixamoCustom/Arissa_Combat.npy
Window count: 24, total frame (without downsampling): 9142
Traceback (most recent call last):
       File "train.py", line 54, in <module>
           main()
       File "train.py", line 23, in main
           dataset = create_dataset(args, characters)
       File "C:\MA-stuff\deep-motion-editing-master\retargeting\datasets\__init__.py", line 32, in create_dataset
           return MixedData(args, character_names)
       File "C:\MA-stuff\deep-motion-editing-master\retargeting\datasets\combined_motion.py", line 86, in __init__
           offsets_group = torch.cat(offsets_group, dim=0)
RuntimeError: Sizes of tensors must match except in dimension 0. Got 25 and 23 in dimension 1 (The offending index is 2)
```

Does anyone know why that happens and what to do to fix it?
Thanks everyone! :)

**Comment by PeizhuoLi** [comment]
It seems that the skeleton structures are different among the provided characters. Maybe you can try to split them into different groups.

**Comment by rainer7** [comment]
Thank you for your answer! :)  Indeed, the Mixamo character "Arissa" caused this error. 
My initial approach was the following:
I downloaded 600 fbx files with 6 different characters from Mixamo - so 100 motions for each character. Then I split them into two groups A and B:
group A: 'Timmy', 'Orzit', 'Arissa'
group B 'Joe', 'Jackie', 'Doozy'

Once I swopped Arissa with a different mixamo character named 'Shae' it worked. 

Though I don't quite understand why, isn't the whole point of this research to cross-retarget between skeletons with different structures? The other characters seem to have different skeleton structures too, but they didn't cause this error.

**Comment by PeizhuoLi** [comment]
You are welcome : )

Yes. The main point of this project is to deal with cross-structure retargeting. Our assumption is that the character in the same group should have the same skeletal structure. And we only deal with the "coarse" skeleton, meaning that we remove skeletons for finger, clothing and bones for other detail deformation. So these characters you mentioned might have different structure in the raw skeletons but share the same coarse skeleton so they can be put in the same group.

**Comment by rainer7** [comment]
Ah ok, thank you, that does make sense! :) 
One last (at least I hope so ;) ) question:
intra retargeting: retargeting of skeletons within group A OR within group B.
cross retargeting: retargeting of skeletons from group A to group B and vice versa. 
So if I understand correctly for both methods I can also use unknown skeletons that share the same skeleton structure but have different proportions.  Skeletons that don't have either the skeleton structure of group A or group B can not be retargeted with the trained model, is that right?

**Comment by PeizhuoLi** [comment]
You are right. If there is an unseen skeletal architecture, our method can't handle it unless you train a new model with dataset of that structure.

Regarding testing, if you mean test.py that contains numerical evaluation, same motion is necessary (as ground truth) to produce numerical error. But if only for inference (retargeting motion from character A to B) then the same motion is of course not necessary: it's what the project is for!
