### ISSUE TITLE
Where is model?

### ISSUE THREAD

**Issue by chenerg** [DeepMotionEditing/deep-motion-editing#13]
Your work is great, and I'm curious about the model for the bvh data. I want to render the animation of Jerry model in your presentation video

**Comment by kfiraberman** [comment]
Thank you for your interest! Applying "skinning" to the output skeletons involves some manual steps which are beyond the scope of this repository (which supplies only the fully automated part of the motion editing and skeleton rendering).

Here is a "quick and dirty" guideline for how to apply skin to the resulting bvh files, with blender:
- Download the fbx file that corresponds to the retargeted character (for example, "[mousy](https://www.mixamo.com/#/?page=1&query=mousy&type=Character)" 
- Import the fbx file to blender (uncheck the "import animation" option)
- Merge meshes - select all the parts and merge them (ctrl+J)
- Import the retargeted bvh file 
- Click "context" (menu bar) -> "Rest Position" (under sekeleton)
- Manually align the mesh and the skeleton (rotation + translation)
- Select the skeleton and the mesh (the skeleton object should be highlighted)
- Click Object -> Parent -> with automatic weights (or Ctrl+P)

Now the skeleton and the skin are bound and you can render the animation.

**Comment by chenerg** [comment]
Thanks for your detailed guidance. This really helps me to render the animation.
