### ISSUE TITLE
Training is successful, but testing does not work 

### ISSUE THREAD

**Issue by DerpyMan101** [DeepMotionEditing/deep-motion-editing#130]
I trained the model and it successfully saved, but when running test.py, this error is outputted

`loading from ./pretrained/models/topology0
loading from epoch 20000......
Traceback (most recent call last):
  File "test.py", line 39, in <module>
    eval(i, prefix)
  File "/home/graham/Desktop/deep-motion-editing-master/retargeting/eval.py", line 25, in eval
    model.load(epoch=20000)
  File "/home/graham/Desktop/deep-motion-editing-master/retargeting/models/architecture.py", line 277, in load
    model.load(os.path.join(self.model_save_dir, 'topology{}'.format(i)), epoch)
  File "/home/graham/Desktop/deep-motion-editing-master/retargeting/models/integrated.py", line 82, in load
    self.auto_encoder.load_state_dict(torch.load(os.path.join(path, 'auto_encoder.pt'),
  File "/home/graham/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for AE:
	size mismatch for enc.layers.0.0.mask: copying a param with shape torch.Size([184, 92, 15]) from checkpoint, the shape in current model is torch.Size([200, 100, 15]).
	size mismatch for enc.layers.0.0.weight: copying a param with shape torch.Size([184, 92, 15]) from checkpoint, the shape in current model is torch.Size([200, 100, 15]).
	size mismatch for enc.layers.0.0.bias: copying a param with shape torch.Size([184]) from checkpoint, the shape in current model is torch.Size([200]).
	size mismatch for enc.layers.0.0.offset_enc.bias: copying a param with shape torch.Size([184]) from checkpoint, the shape in current model is torch.Size([200]).
	size mismatch for enc.layers.0.0.offset_enc.weight: copying a param with shape torch.Size([184, 69]) from checkpoint, the shape in current model is torch.Size([200, 75]).
	size mismatch for enc.layers.0.0.offset_enc.mask: copying a param with shape torch.Size([184, 69]) from checkpoint, the shape in current model is torch.Size([200, 75]).
	size mismatch for enc.layers.0.1.weight: copying a param with shape torch.Size([96, 184]) from checkpoint, the shape in current model is torch.Size([120, 200]).
	size mismatch for enc.layers.1.0.mask: copying a param with shape torch.Size([192, 96, 15]) from checkpoint, the shape in current model is torch.Size([240, 120, 15]).
	size mismatch for enc.layers.1.0.weight: copying a param with shape torch.Size([192, 96, 15]) from checkpoint, the shape in current model is torch.Size([240, 120, 15]).
	size mismatch for enc.layers.1.0.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([240]).
	size mismatch for enc.layers.1.0.offset_enc.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([240]).
	size mismatch for enc.layers.1.0.offset_enc.weight: copying a param with shape torch.Size([192, 72]) from checkpoint, the shape in current model is torch.Size([240, 90]).
	size mismatch for enc.layers.1.0.offset_enc.mask: copying a param with shape torch.Size([192, 72]) from checkpoint, the shape in current model is torch.Size([240, 90]).
	size mismatch for enc.layers.1.1.weight: copying a param with shape torch.Size([112, 192]) from checkpoint, the shape in current model is torch.Size([112, 240]).
	size mismatch for dec.layers.0.1.weight: copying a param with shape torch.Size([192, 112]) from checkpoint, the shape in current model is torch.Size([240, 112]).
	size mismatch for dec.layers.0.2.mask: copying a param with shape torch.Size([96, 192, 15]) from checkpoint, the shape in current model is torch.Size([120, 240, 15]).
	size mismatch for dec.layers.0.2.weight: copying a param with shape torch.Size([96, 192, 15]) from checkpoint, the shape in current model is torch.Size([120, 240, 15]).
	size mismatch for dec.layers.0.2.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([120]).
	size mismatch for dec.layers.0.2.offset_enc.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([120]).
	size mismatch for dec.layers.0.2.offset_enc.weight: copying a param with shape torch.Size([96, 72]) from checkpoint, the shape in current model is torch.Size([120, 90]).
	size mismatch for dec.layers.0.2.offset_enc.mask: copying a param with shape torch.Size([96, 72]) from checkpoint, the shape in current model is torch.Size([120, 90]).
	size mismatch for dec.layers.1.1.weight: copying a param with shape torch.Size([184, 96]) from checkpoint, the shape in current model is torch.Size([200, 120]).
	size mismatch for dec.layers.1.2.mask: copying a param with shape torch.Size([92, 184, 15]) from checkpoint, the shape in current model is torch.Size([100, 200, 15]).
	size mismatch for dec.layers.1.2.weight: copying a param with shape torch.Size([92, 184, 15]) from checkpoint, the shape in current model is torch.Size([100, 200, 15]).
	size mismatch for dec.layers.1.2.bias: copying a param with shape torch.Size([92]) from checkpoint, the shape in current model is torch.Size([100]).
	size mismatch for dec.layers.1.2.offset_enc.bias: copying a param with shape torch.Size([92]) from checkpoint, the shape in current model is torch.Size([100]).
	size mismatch for dec.layers.1.2.offset_enc.weight: copying a param with shape torch.Size([92, 69]) from checkpoint, the shape in current model is torch.Size([100, 75]).
	size mismatch for dec.layers.1.2.offset_enc.mask: copying a param with shape torch.Size([92, 69]) from checkpoint, the shape in current model is torch.Size([100, 75]).
	size mismatch for dec.unpools.0.weight: copying a param with shape torch.Size([192, 112]) from checkpoint, the shape in current model is torch.Size([240, 112]).
	size mismatch for dec.unpools.1.weight: copying a param with shape torch.Size([184, 96]) from checkpoint, the shape in current model is torch.Size([200, 120]).
	size mismatch for dec.enc.layers.0.0.mask: copying a param with shape torch.Size([184, 92, 15]) from checkpoint, the shape in current model is torch.Size([200, 100, 15]).
	size mismatch for dec.enc.layers.0.0.weight: copying a param with shape torch.Size([184, 92, 15]) from checkpoint, the shape in current model is torch.Size([200, 100, 15]).
	size mismatch for dec.enc.layers.0.0.bias: copying a param with shape torch.Size([184]) from checkpoint, the shape in current model is torch.Size([200]).
	size mismatch for dec.enc.layers.0.0.offset_enc.bias: copying a param with shape torch.Size([184]) from checkpoint, the shape in current model is torch.Size([200]).
	size mismatch for dec.enc.layers.0.0.offset_enc.weight: copying a param with shape torch.Size([184, 69]) from checkpoint, the shape in current model is torch.Size([200, 75]).
	size mismatch for dec.enc.layers.0.0.offset_enc.mask: copying a param with shape torch.Size([184, 69]) from checkpoint, the shape in current model is torch.Size([200, 75]).
	size mismatch for dec.enc.layers.0.1.weight: copying a param with shape torch.Size([96, 184]) from checkpoint, the shape in current model is torch.Size([120, 200]).
	size mismatch for dec.enc.layers.1.0.mask: copying a param with shape torch.Size([192, 96, 15]) from checkpoint, the shape in current model is torch.Size([240, 120, 15]).
	size mismatch for dec.enc.layers.1.0.weight: copying a param with shape torch.Size([192, 96, 15]) from checkpoint, the shape in current model is torch.Size([240, 120, 15]).
	size mismatch for dec.enc.layers.1.0.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([240]).
	size mismatch for dec.enc.layers.1.0.offset_enc.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([240]).
	size mismatch for dec.enc.layers.1.0.offset_enc.weight: copying a param with shape torch.Size([192, 72]) from checkpoint, the shape in current model is torch.Size([240, 90]).
	size mismatch for dec.enc.layers.1.0.offset_enc.mask: copying a param with shape torch.Size([192, 72]) from checkpoint, the shape in current model is torch.Size([240, 90]).
	size mismatch for dec.enc.layers.1.1.weight: copying a param with shape torch.Size([112, 192]) from checkpoint, the shape in current model is torch.Size([112, 240]).
`

**Comment by PeizhuoLi** [comment]
Hi, this exception can be triggered by many causes. It could be helpful to provide more details, e.g. on which dataset you trained the model.

**Comment by DerpyMan101** [comment]
The dataset that I used was obtained by following the instructions on how to make a dataset here: https://github.com/DeepMotionEditing/deep-motion-editing#dataset-1, so I had two seperate models, and then followed those instructions.

**Comment by hamza-projectz** [comment]
Can you solve this issue? I just faced the same issue.
