### ISSUE TITLE
请问可以提供retarget工作的bvh文件或者fbx文件吗

### ISSUE THREAD

**Issue by ucaswindlike** [DeepMotionEditing/deep-motion-editing#135]
你好，我想跟你们的工作做一个对比，想用相同的训练集和测试集，我们的数据处理方式不一样，请问可以提供原始的fbx或者bvh文件吗，万分感谢

**Comment by PeizhuoLi** [comment]
你好，带bvh的链接在[这里](https://disk.pku.edu.cn:443/link/38BA4A625A8A40C801CE44538DFB8928)
