### ISSUE TITLE
如何使用自己的content进行style transfer？

### ISSUE THREAD

**Issue by Molicaliatimis** [DeepMotionEditing/deep-motion-editing#136]
您好，我有一段自己的bvh动作，现在想使用您的模型对它进行风格转换。但是我的bvh和您demo中作为content的bvh并不匹配，两者的骨骼结构略有差异。我尝试进行Motion Retargeting，但是没有找到您在style transfer的demo中使用的那个角色的骨架。请问您有解决方案吗？

**Comment by HalfSummer11** [comment]
您好，我们的模型是训练与测试在 [这个CMU骨架](https://github.com/DeepMotionEditing/deep-motion-editing/blob/0efe8831709d15f8a7c58d504b0b4f71d9ee11eb/style_transfer/global_info/rest.bvh)上的，希望可以帮到您。
