### ISSUE TITLE
使用blender将fbx转bvh的疑问

### ISSUE THREAD

**Issue by Vincent-2017** [DeepMotionEditing/deep-motion-editing#137]
你好，我使用fbx2bvh.py转换的一个fbx文件成bvh未作其他任何处理，但是在maya里查看原始的fbx中某些关节的offset和旋转与blender转换后bvh中不一致，但有些又是一样的，这是什么原因呢？
![image](https://user-images.githubusercontent.com/26915856/109742054-50f95700-7c09-11eb-92ea-686a184c4ca0.png)
![image](https://user-images.githubusercontent.com/26915856/109742139-82722280-7c09-11eb-990c-a576c064712a.png)

**Comment by happyday521** [comment]
@Vincent-2017 你好，我也遇到了类似的问题，请问你解决了吗？
