### ISSUE TITLE
Request for Characters with "_M

### ISSUE THREAD

**Issue by isjang08** [DeepMotionEditing/deep-motion-editing#138]
Hi, 
I'm a graduate student researching motion retargeting. I am excited about your work and paper. 
I ran your code and tested the network on new motion data with  Mixamo. 
I noticed characters with "_m" is not same as them in Mixamo. 
Could you provide me these 4 characters?

Thanks in advance.

**Comment by PeizhuoLi** [comment]
Duplicated issue.
