### ISSUE TITLE
Blender Visualization

### ISSUE THREAD

**Issue by Hellodan-77** [DeepMotionEditing/deep-motion-editing#143]
Hello! I would like to ask if blender's python API (2.80) needs to be installed in this part of blender_rendering? Can BVH be visualized by running load_bvh.py directly? Because I don’t understand this part in the github page, I hope to receive your reply!

**Comment by HalfSummer11** [comment]
If you want a quick visualization just to check the motion quality (instead of rendering a video), you can directly import the BVH file into Blender, which doesn't require any python. The python API is needed for a full rendering.

**Comment by Hellodan-77** [comment]
How does the "blender_rendering" part of your code work? Do I need to install any related software? Or just run load_bvh.py directly? Do you have relevant reference links? If so, please share with me, thank you very much!

**Comment by Hellodan-77** [comment]
Now I want to use the "blender_rendering" part of your code for BVH visualization. I don't know how to do it at the beginning. I hope to get your help.

**Comment by PeizhuoLi** [comment]
Blender's Python API is built-in when you install blender. You only need to add scipy module to blender to run the scrip. You can find details about it in Blender Visualization section in README. Also, you can run load_bvh.py with blender to visualize and it is also described in readme.
