### ISSUE TITLE
测试一个新的骨架，还需要该骨架的运动信息吗？

### ISSUE THREAD

**Issue by sunbin1357** [DeepMotionEditing/deep-motion-editing#145]
针对retargeting，论文中提到只需要测试的骨架信息就可以。但是在demo.py中我发现，还需要测试骨架的运动信息，这是为什么？
NKN的论文中也提到了：
Input motion is seen during training, and the target character is also seen during training but the target motion sequence is not.

**Comment by PeizhuoLi** [comment]
不需要运动信息。demo.py仅仅是吧ground-truth复制了一份方便对比结果
