### ISSUE TITLE
The format of extracting bones from video by OpenPose

### ISSUE THREAD

**Issue by evelesliexx** [DeepMotionEditing/deep-motion-editing#147]
Hi :) 
I want to use OpenPose to extract the skeleton in my video and then transfer the style, but there will be an error prompt of IK operation: **_[Jacobian inverse kinematics] iteration 10 | error: 0.212351_**
Can you tell me the specific format of openpose bone point data you use? Did it include the hand bone points?
I just can't see the characteristics from the JSON file.
Thank you!

**Comment by HalfSummer11** [comment]
Hi :) This is probably not an error message. "Error" here represents the amount of error (average distance from the actual joint positions to the target joint positions) in the current IK optimization iteration. 
We enable `--hand` option when we use OpenPose so the JSON files should include hand joints.
