### ISSUE TITLE
style transfer

### ISSUE THREAD

**Issue by Hellodan-77** [DeepMotionEditing/deep-motion-editing#148]
Hello! I would like to ask in "style_transfer", in the file utils/animation_2d_data.py, in from_openpose_json,
In the code file, joint_map has
```
joint_map = {
0: 8,
1: 12, 2: 13, 3: 14, 4: 19,
5: 9, 6: 10, 7: 11, 8: 22,
# 9 is somewhere between 0 & 10
10: 1,
# 11 is somewhere between 10 and 12
12: 0,
13: 5, 14: 6, 15: 7, # 16 is a little bit further
17: 2, 18: 3, 19: 4, # 20 is a little bit further
}
```
For example, before and after the colon: (0:8) If it is x:y, what does each corresponding x and y represent?

**Comment by HalfSummer11** [comment]
Here x represents a joint index in the CMU skeleton, and y represents the corresponding joint index in the raw output from OpenPose. (see [line 93](https://github.com/DeepMotionEditing/deep-motion-editing/blob/0efe8831709d15f8a7c58d504b0b4f71d9ee11eb/utils/animation_2d_data.py#L93))
