### ISSUE TITLE
Can this be used with other 3D programs and different rigs?

### ISSUE THREAD

**Issue by delebash** [DeepMotionEditing/deep-motion-editing#15]
I use reallusion [iClone ](https://www.reallusion.com/)and Character Creator which are similar to [DAZ3D](https://www.daz3d.com/).  

What I am looking for is to have full body motion capture face and hands from a web camera.

One of the problems I have been running into using Character Creator 3 armature is that the facial movement is mostly based on BlendShapes (Morphs) and I don't know how to translate that from xyz coordinates.  Actually I am just learning 3D and motion capture  but the price for markerless mocap is high and I am just a hobbyist so I have been searching for an opensource solution.

Your software looks it will be fantastic!

Thanks,
Dan

**Comment by kfiraberman** [comment]
Thanks for your comment.
It seems like our provided code can't assist your problem within Character Creator 3, as we do not deal with such data formats.

**Comment by delebash** [comment]
Thanks
