### ISSUE TITLE
Generate the gif demo

### ISSUE THREAD

**Issue by LeVan146** [DeepMotionEditing/deep-motion-editing#151]
Hi authors, I'm able to generate the video file from your code, thx. 
- But I want to generate the gif file like your work (like this one [gif file](https://github.com/DeepMotionEditing/deep-motion-editing/blob/master/images/style_transfer_teaser.gif))
- I try to use PIL/imageio lib to generate the gif from video, but my gif kinda lagging, maybe because of the "fps" and "duration" parameters, but I'm not sure how to make it smooth like your gif.
- I use PIL/imageio lib because I want to auto-generate the text in gif file.

I hope you can give me some idea to generate the gif like you, thank you in advance.

**Comment by HalfSummer11** [comment]
Hi! I'm sorry that I'm not familiar with PIL/imageio. In our case, the gif file is generated by Adobe Premiere (for putting multiple video together + adding text. In fact, you can directly export a GIF file with Premiere) and GIF Brewery (for converting videos to gifs, where you can tune the parameters to balance between quality and size).
