### ISSUE TITLE
I did not find the appendix mentioned in the Style Transfer paper in your open source materials

### ISSUE THREAD

**Issue by eveleslie** [DeepMotionEditing/deep-motion-editing#152]
Hi!  :)
I have read your paper intensively these days, and it mentioned "A detailed description of the architecture layers and parameters is given in the Appendix." on the fourth page, but I did not find the appendix you mentioned. 
Would you please provide it?I want to know more about the network structure and specific details of your article.
Thanks a lot!!!!

**Comment by HalfSummer11** [comment]
Hi :) Thanks for your interest in our work!
We're sorry that we didn't have the appendix either -- it was never written, and what you see in the paper is a typo we forgot to remove 😢 
The architecture is defined in [networks.py](https://github.com/DeepMotionEditing/deep-motion-editing/blob/master/style_transfer/networks.py). The parameters can be found in [config.py](https://github.com/DeepMotionEditing/deep-motion-editing/blob/master/style_transfer/config.py). We're sorry for the inconvenience.

**Comment by eveleslie** [comment]
Ok I see!
Thank you for your prompt reply!!!

**Comment by Pcookie** [comment]
> Hi :) Thanks for your interest in our work! We're sorry that we didn't have the appendix either -- it was never written, and what you see in the paper is a typo we forgot to remove 😢 The architecture is defined in [networks.py](https://github.com/DeepMotionEditing/deep-motion-editing/blob/master/style_transfer/networks.py). The parameters can be found in [config.py](https://github.com/DeepMotionEditing/deep-motion-editing/blob/master/style_transfer/config.py). We're sorry for the inconvenience.
大佬 救救 我给你邮箱发邮件了   我是个小白  关于风格化转移有些问题想要请教  比如我用自己的数据训练出的模型（重定向部分）然后使用该模型生成了一份重定向后的bvh  想将某个风格转移给该BVH时遇到困难
