### ISSUE TITLE
Understand the code.

### ISSUE THREAD

**Issue by LeVan146** [DeepMotionEditing/deep-motion-editing#156]
Hi guys, I'm self-learning about this project. So I have difficulty understanding some code/setting/meaning in this project.
I hope you can explain some questions for me. Thank ^^

My first question is What is the offset? Why we only need 1 xia offset for all data point?
- From my understanding, offset in animation is something to make the rotation smoother, but I'm not sure its purpose in this project.
https://github.com/DeepMotionEditing/deep-motion-editing/blob/19604abdc0ead66f8c82d9211b8c5862c6a68089/style_transfer/global_info/skeleton_CMU.yml#L3-L34

The second is why we have to update transform by its parent transform?
https://github.com/DeepMotionEditing/deep-motion-editing/blob/19604abdc0ead66f8c82d9211b8c5862c6a68089/utils/animation_data.py#L34-L35

Moreover, I hope you can give me some good books to learn about the math behind skeleton in animation. Because when I search in google, most of the result only gives me about code from Unity without math equation behind it.

**Comment by kfiraberman** [comment]
Hi, the "offsets" represent the bones of the skeleton. You can think of it as a set of 3D vectors, where each vector connects between two joints. In the style transfer work, we assume that the skeleton is fixed, so we need one set of "offsets".

The reason for the "parent" transform is that in animation it's common to work in a hierarchical structure (of joints).

To get more details, I suggest learning about the BVH representation (the common format for representing skeletal animations). [This post](http://forum.maratis3d.com/viewtopic.php?id=59) shares some good resources for that. Good luck!

**Comment by LeVan146** [comment]
Thank you for your advice ^^
