### ISSUE TITLE
Epochs need to train model

### ISSUE THREAD

**Issue by fire** [DeepMotionEditing/deep-motion-editing#160]
What is a good way to guess the number of epochs to train the model? Is there a minimum?

**Comment by PeizhuoLi** [comment]
Hi, our experiment suggests that 5,000 epochs should be enough for most dataset. The reconstruction loss on quaternions is also a good indicator about the result, a reasonable result should reach at least less than 0.015

**Comment by fire** [comment]
Can you explain how to determine reconstruction loss? Is that like every 50 epochs test loss? Hiw would I do that?

**Comment by fire** [comment]
Thanks for answering the question. Will close now.
