### ISSUE TITLE
About Intra-Structure Training On Custom dataset 

### ISSUE THREAD

**Issue by FishWoWater** [DeepMotionEditing/deep-motion-editing#162]
Hi! Thanks for your nice work! 

I have a question when considering intra-structure training setting on my custom dataset. The encoder learns latent code from offsets and rotations of `model A`, and then given offsets of `model B`, the encoder is expected to output rotations conditioned on those offsets, right? I guess bone proportion difference is addressed in this way, but I am wondering whether such practice is robust to different initial poses(e.g. `model A` and `model B` has different initial poses). And if I have limited number of characters (less than 10 or even less than 5), I am wondering whether the generalization ability to different initial pose will be affected. 

Looking forward to your reply, thanks! @kfiraberman @PeizhuoLi

**Comment by PeizhuoLi** [comment]
Hi, thank you for your interest in our project. 

You are right. Generally we expect the initial pose to be in similar T-pose. Non T-pose input could lead to failure, especially when there are only a few training characters. I would recommend you to retarget the rest pose in T-pose before using our code.

**Comment by FishWoWater** [comment]
OK, thanks!
