### ISSUE TITLE
Can Unpaired Motion Style Transfer be adjusted?

### ISSUE THREAD

**Issue by delebash** [DeepMotionEditing/deep-motion-editing#17]
From looking at both videos I see that this is being designed for "intelligent ai retargeting  and stylized motion.  Can the strength of the stylized motion be adjusted?  Is this project related to [FACS AU](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Action-Units) as far as using emotions for mocap instead of direct xyz?

Thanks!

**Comment by kfiraberman** [comment]
I'm not sure that I understand your question. 
In general, the framework of our "Unpaired motion style transfer" can be generalized to other domains as long as the dataset consists of a few (labeled) groups (e.g., styles), where the distribution of the complementary property within each group (e.g, content) is roughly equal.

**Comment by delebash** [comment]
I think I am the one who misunderstood how your program works.  It is very nice and I am looking forward to continued development!

Thanks!
Dan
