### ISSUE TITLE
请问在自己骨骼上做重定向的步骤

### ISSUE THREAD

**Issue by shinshiner** [DeepMotionEditing/deep-motion-editing#170]
你好，感谢分享这两篇工作。我尝试使用预训练模型在自己的骨骼上做重定向，即把Aj骨骼上的动作迁移到自己的骨骼（或者反过来），但是效果不如预期，参考之前的issue，最后的步骤如下，请问有什么错误吗？
1. 骨骼是CMU数据集的骨骼，先用split_joint分割成topology1的28个关节；
2. 因为只有一个bvh动作数据，所以把它作为std_bvh，同时用来算mean和var；
3. 运行demo.py

最后的结果不管迁移顺序如何，人物都只会做一些无规律的旋转，请问上面的步骤有错误吗？因为只有很少的数据，应该没法重新训练模型。

**Comment by shinshiner** [comment]
另外，从std_bvh里得到的似乎只有关节的offset？同个骨骼在不同bvh文件的offset应该都是一样的，为什么之前的issue提到需要保证和T-pose接近呢？

**Comment by PeizhuoLi** [comment]
已经收到了你询问同样问题的邮件，因此将该issue关闭
