### ISSUE TITLE
Can it retarget from  humans to animals？

### ISSUE THREAD

**Issue by Macile** [DeepMotionEditing/deep-motion-editing#173]

**Comment by PeizhuoLi** [comment]
Hi, we've tried to retarget between gorilla and dog but the result doesn't look convincing (see our supp. video [here](https://www.youtube.com/watch?v=ym8Tnmiz5N8&t=331s)). So it can be non-trivial to directly use this work to retarget between human and animal.

**Comment by Macile** [comment]
> Hi, we've tried to retarget between gorilla and dog but the result doesn't look convincing (see our supp. video [here](https://www.youtube.com/watch?v=ym8Tnmiz5N8&t=331s)). So it can be non-trivial to directly use this work to retarget between human and animal.

I get it. thank you
