### ISSUE TITLE
run python test.py error ,maybe some error in code 

### ISSUE THREAD

**Issue by hitxuhao** [DeepMotionEditing/deep-motion-editing#18]
python test.py 
Batch [1/4]
Error: Numpy + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp-7c85b1e2.so.1 library.
	Try to import numpy first or set the threading layer accordingly. Set NPY_MKL_FORCE_INTEL to force it.
Collecting test error...
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    cross_error += full_batch(0)
  File "/home/linux/workspace/skeletonAware/deep-motion-editing-master/retargeting/get_error.py", line 15, in full_batch
    res.append(batch(char, suffix))
  File "/home/linux/workspace/skeletonAware/deep-motion-editing-master/retargeting/get_error.py", line 54, in batch
    err = (pos - pos_ref) * (pos - pos_ref)
ValueError: operands could not be broadcast together with shapes (108,28,3) (156,28,3)

**Comment by PeizhuoLi** [comment]
Hi, it seems I can't reproduce the same error.  According to your report, there could be something wrong with your environment configuration of numpy and MKL. If you can provide more information, e.g. platform, environment, it might be helpful.

**Comment by PeizhuoLi** [comment]
Hi, we recently enhanced compatibility. Hope the latest commit helps.
