### ISSUE TITLE
quaternion loss in the code

### ISSUE THREAD

**Issue by Yuefengxin** [DeepMotionEditing/deep-motion-editing#183]
Thanks for your great Job! 
I have difficulty understanding some code in this project. I don't see this term in the loss function in the paper. 
```
            # quaternion loss -> norm = 1
            l_qt_t, l_tw_t = self.rot_loss_from_raw(rxt)
            l_qt_r, l_tw_r = self.rot_loss_from_raw(rxr)
            l_qt_s, l_tw_s = self.rot_loss_from_raw(rxs)

            l_qt_rec = (l_qt_r + l_qt_s) / 2.0
            l_qt = self.weighted_average(l_qt_t, l_qt_rec)
            l_tw_rec = (l_tw_r + l_tw_s) / 2.0
            l_tw = self.weighted_average(l_tw_t, l_tw_rec)
```
Could you please tell me what this means? Thanks ^^

**Comment by HalfSummer11** [comment]
Hi, thanks for your question. The "rot_loss_from_raw" contains a set of losses that push raw network outputs closer to a "good quaternion". First, the quaternion's norm should be close to 1 (unit quaternion). This explains `l_qt`. Second, the rotation("twist") shouldn't be too large, and this is the twist loss `l_tw`. 

Our twist loss follows the practice of [Villegas, R., Yang, J., Ceylan, D., & Lee, H. (2018). Neural Kinematic Networks for Unsupervised Motion Retargetting] (Sec 4.2). It is meant to avoid "excessive bone twisting" (e.g. unnecessary rotation around a symmetric axis) and penalizes rotations greater than alpha. Our code is also adapted from [their implementation](https://github.com/rubenvillegas/cvpr2018nkn/blob/41c2a304484daccdb8f59808c71d9543b38a8559/src/online_retargeting_model.py#L149).

Hope this helps.

**Comment by Yuefengxin** [comment]
Thank you very much for your response. It helps me a lot!
