### ISSUE TITLE
关于bvh文件中欧拉角的旋转轴

### ISSUE THREAD

**Issue by happyday521** [DeepMotionEditing/deep-motion-editing#192]
Hi, 我有关于bvh文件中节点旋转表示的问题向您请教：
在标准的bvh文件中，yrotation, xrotation, zrotation所对应的欧拉角的旋转轴是相对于什么坐标系而言的？是基于世界坐标系(外旋) or 该节点所对应父节点的局部坐标系（内旋）？
谢谢！

**Comment by PeizhuoLi** [comment]
你好， 是相对于父节点的局部坐标

**Comment by happyday521** [comment]
谢谢回答！

再问一下，在bvh文件中，表示T-pose的offset是基于坐标系计算的呢？是子节点的世界坐标跟父节点的世界坐标相减？ or 以父节点作为原点，计算该节点在父节点的局部坐标系的位置？
谢谢！

**Comment by PeizhuoLi** [comment]
Offset也是表示的这个关节在父关节坐标系下的位置。如果要计算一个关节在T-pose下的世界坐标，就需要把它到根结点的所有offset加起来

**Comment by happyday521** [comment]
了解了，非常感谢您的回答！

**Comment by happyday521** [comment]
不好意思，再请问您一个问题。
在T-pose下，所有关节的局部坐标系的朝向（x、y、z轴的方向）是都保持一致吗？是不是都跟世界坐标系的朝向一样？

根据我的理解，在所有关节的局部坐标系的朝向跟世界坐标系一致时，才能直接累计offset来计算一个关节在T-pose下的世界坐标。请您指教，谢谢！

**Comment by PeizhuoLi** [comment]
是的，T-pose下所有关节的局部坐标系都和世界坐标系一致

**Comment by happyday521** [comment]
收到，谢谢回复！
