### ISSUE TITLE
关于bvh数据中旋转矩阵的顺序

### ISSUE THREAD

**Issue by happyday521** [DeepMotionEditing/deep-motion-editing#195]
你好，我有关于bvh文件中节点旋转顺序的问题向您请教：

在BVH 数据中, 关键字“CHANNELS”后面旋转通道的顺序是“Zrotation”,“Xrotation”, “Yrotation”, 根据我的理解，这表示子节点绕其**父节点的局部坐标轴**的旋转先后顺序为**z, x, y** 轴。在子节点的旋转过程中，因为其父节点的局部坐标轴保持固定，因此**子节点的旋转可以视为相对其父节点的局部坐标轴的外旋**。这样，该子节点的旋转矩阵可以写为：**R=R(y) R(x) R(z)**。

但是，在deep-motion-editing/utils/Quaternions.py 代码的from_euler（）函数中（line 417- 429），在order=‘zxy’时，因为world=False，所以最后return的结果是 **q0s * (q1s * q2s)**（即R=R(z) R(x) R(y)）；而不是我所理解的**q2s * (q1s * q0s)**（即R=R(y) R(x) R(z)）。请问我哪里理解错了？
![image](https://user-images.githubusercontent.com/35884085/138403990-80ffe435-d081-44c2-b1a8-c4e490a07fc6.png)

谢谢，期待您的回复！

**Comment by happyday521** [comment]
或者是：在BVH 数据中“CHANNELS”后面旋转通道的顺序“Zrotation”,“Xrotation”, “Yrotation”,表示子节点绕其**自身局部坐标轴**的旋转先后顺序为z, x, y 轴，即**子节点的旋转可以视为相对其自身局部坐标轴的内旋**？ 这样，该子节点的旋转矩阵可以写为：R=R(z) R(x) R(y)。跟您deep-motion-editing/utils/Quaternions.py 代码的from_euler（）函数的返回值一致。
请问这样理解对吗？

**Comment by PeizhuoLi** [comment]
你好，按照BVH文件的[定义](https://research.cs.wisc.edu/graphics/Courses/cs-838-1999/Jeff/BVH.html)，MOTION节的euler angle都是intrinsic的。你的理解没问题！

**Comment by Pcookie** [comment]
老师  我找不到李老师   您之前研究过这个项目  我想请教一些问题  我太小白了  能加个好友请教吗  13270722390@163.com
