### ISSUE TITLE
论文中的动作可视化

### ISSUE THREAD

**Issue by Yuefengxin** [DeepMotionEditing/deep-motion-editing#199]
@PeizhuoLi  你好，感谢分享！方便问一下论文中下图这种同时显示多帧的可视化是怎么做的吗？如果是用Blender，请问可以分享相关的教程吗？我尝试复制多个物体，但是不知道怎么修改每一个的时间线。谢谢！
<img width="183" alt="aberman" src="https://user-images.githubusercontent.com/46143512/144778992-f85a7b03-a85c-4827-bf70-6e01d7fe4260.PNG">

**Comment by PeizhuoLi** [comment]
你好，有两个解决方案：

1. 逐帧渲染然后使用图片编辑器把他们拼在一起

2. 生成多个bvh文件，每个文件的第一帧对应你想渲染的帧，然后导入多个bvh一起渲染
