### ISSUE TITLE
Scale about the BVH file converted from FBX file

### ISSUE THREAD

**Issue by jinnan-chen** [DeepMotionEditing/deep-motion-editing#202]
Hi, thanks for the inspiring work!

I have a question about the scale ratio between the BVH file converted from FBX file with the original FBX 3D mesh. It seems the scale is not the same when I import them into blender. 

Thanks!

**Comment by PeizhuoLi** [comment]
Hi, I also had the same problem. But in my experience the scaling the skeleton imported from bvh by 0.01 and rotating it along some axis for 90 degrees should align it to the 3D mesh. I'm no expert of FBX file, but I guess there is some property specifying the rotation and scaling in the file and it might be abandoned by blender when exporting as bvh file.

**Comment by jinnan-chen** [comment]
Yes, I import them together to blender and also feel like some number around 0.01 is the right ratio but without rotation, I converted the corresponding FBX to the keypoints coordinates and I attach a screen shot here. The keypoints are like a tight cage of the mesh. So maybe that is a little smaller than 0.01.
<img width="380" alt="WechatIMG44" src="https://user-images.githubusercontent.com/53347259/160160889-eb778b1e-fb46-4cfe-8560-8c02814ef166.png">
