### ISSUE TITLE
Request for training dataset

### ISSUE THREAD

**Issue by loveyourdaddy** [DeepMotionEditing/deep-motion-editing#204]
Thank you all authors for the great and awesome work in Siggraph 2020. 
It still inspires all researchers in 2022. 

I am a Ph.D. student studying motion retargeting.  
You release the preprocessed training dataset, but could you also open the original raw bvh training dataset also?

Thanks!

**Comment by PeizhuoLi** [comment]
Hi, thanks for your question. Unfortunately, the Mixamo dataset is created by Adobe and we do not have the permission to redistribute it. However, you can find a useful instruction to download it yourself in [this](https://github.com/ChrisWu1997/2D-Motion-Retargeting/blob/master/dataset/Guide%20For%20Downloading%20Mixamo%20Data.md) link.
