### ISSUE TITLE
非标准躯干数据集的可能性

### ISSUE THREAD

**Issue by dddyyyplus** [DeepMotionEditing/deep-motion-editing#211]
李老师您好！
我想咨询一下就是我现在有一份不标准的躯干的bvh数据，这是因为我选取了一套挥杆动作，高尔夫球杆绑定在人的左手上，也就是左手会比右手多出一些关节，这样不对称的躯干会对训练产生影响吗，我自己尝试训练了一下并尝试了intra的重定向但是效果很不理想，是因为末梢点变成了球杆的末梢导致的吗，烦请李老师百忙之余回答一下，感谢！
![WechatIMG46](https://user-images.githubusercontent.com/45458872/191406429-18c901f6-e640-4e9d-9e2f-e46029987b02.png)        ![WechatIMG45](https://user-images.githubusercontent.com/45458872/191406420-d630f01d-d5b5-4a48-bf06-b1db988a4601.jpeg)

**Comment by PeizhuoLi** [comment]
您好，类似的情况我们在实验中是可以解决的 (如论文中的figure 12)。intra的retargeting应该是相对容易的，通常只要reconstruction loss收敛就可以达到比较理想的效果。如果intra效果不好的话不妨检查一下reconstruction loss方面的问题。

**Comment by dddyyyplus** [comment]
好的，李老师，我在自己实验一下，还有一个问题就是训练时有的人物的动作数据比较少，可能只有两三个bvh文件这样，是否会导致这个模型的重定向效果较差？如果没有办法得到更多的数据应该怎么解决呢，不知道李老师您有什么建议？感谢！

**Comment by PeizhuoLi** [comment]
据我所知数据不足的问题目前还没有比较好的解决方法；不过如果训练数据的动作能较好的覆盖测试集的话效果应该不会太糟糕

**Comment by dddyyyplus** [comment]
好的，感谢！

**Comment by dddyyyplus** [comment]
> 据我所知数据不足的问题目前还没有比较好的解决方法；不过如果训练数据的动作能较好的覆盖测试集的话效果应该不会太糟糕

不好意思还要再麻烦您一下，我想问“训练数据的动作能较好的覆盖测试集的话效果应该不会太糟糕”
我举个比较实际的例子，如果是将group A的动作重定向到group B一个角色身上，这个训练数据的动作是说A的训练数据还是B的呢，例如我group B 中角色的动作都是高尔夫挥杆动作，那么A的一个日常动作重定向到B身上是否会因为B的训练数据太过单一而不好呢？感谢您的回复！

**Comment by dddyyyplus** [comment]
> 

@PeizhuoLi 辛苦李老师空闲之余回答一下我的疑问，感谢！

**Comment by PeizhuoLi** [comment]
我认为你举的这个例子是不一定可以成功的，需要双向的数据都有一些才会比较容易成功

**Comment by dddyyyplus** [comment]
好的，感谢🙏
