### ISSUE TITLE
BVH_mod

### ISSUE THREAD

**Issue by Yopla38** [DeepMotionEditing/deep-motion-editing#215]
Hello,

Thanks for this code.
I have an error :
import BVH_mod as BVH
ModuleNotFoundError: No module named 'BVH_mod'

Do you have an idea ?
Thanks

**Comment by PeizhuoLi** [comment]
BVH_mode file is under [this](https://github.com/DeepMotionEditing/deep-motion-editing/blob/master/utils/BVH_mod.py) directory. You might need to manually add the path to $PYTHONPATH.
