### ISSUE TITLE
Error in forward kinematics

### ISSUE THREAD

**Issue by abcyzj** [DeepMotionEditing/deep-motion-editing#216]
https://github.com/DeepMotionEditing/deep-motion-editing/blob/74fff8fb35e6378351d03fb14ee22fccae28b0bf/retargeting/models/Kinematics.py#L75
The above line of code is wrong. It should be
```python
result[..., i, :] = torch.matmul(transform[..., pi, :, :], offset[..., i, :, :]).squeeze() 
```
I've already double-checked that with the modified line, the results are coherent with `Blender BVH Importer`'s results.

**Comment by PeizhuoLi** [comment]
Hi, thanks for opening the issue. However, as we are using edge representation (see Sec. 4.1 Motion Representation of the paper), the implementation is different from the BVH convention ([here](https://github.com/PeizhuoLi/ganimator/blob/2943064b456d13f0357e23e3c37fb43b6aa3fdaa/models/kinematics.py#L120) is the implementation of FK in another project using the BVH convention, and this one is the same as what you are posting here).

**Comment by abcyzj** [comment]
Sorry, I got confused. Thanks for your explanation.
