### ISSUE TITLE
how to obtain training dataset?

### ISSUE THREAD

**Issue by crissallan** [DeepMotionEditing/deep-motion-editing#22]
Hi, thanks for sharing such a great project! Howver, I'd like to know that is there any way to obtain or create some customized trainig data?
Because I'd like to reproduce the fully pipeline of the project!
Many thanks!

**Comment by kfiraberman** [comment]
We currently provide the training set of the "style transfer" model, which can be re-trained.
In the near future, we will also provide the training data and procedure for the retargeting model.
