### ISSUE TITLE
How much hard disk space is required, How long is the training

### ISSUE THREAD

**Issue by huanghe036-coder** [DeepMotionEditing/deep-motion-editing#24]

**Comment by PeizhuoLi** [comment]
Training a new model does not require much disk space in addition to storing data sets. Training time varies greatly on different PCs. Please refer to our papers for training time on our PC and its hardware equipment.

**Comment by huanghe036-coder** [comment]
Training... 200g hard disk is almost full

**Comment by HalfSummer11** [comment]
Could you try setting the 'for_try' option in style_transfer/config.py to 'False'? The training process will produce additional outputs, e.g. cluster visualization and intermediate transfer results. And setting 'for_try = True' will result in a very high output frequency and quickly flood your disk. 
We're sorry for the inconvenience and we'll provide a more user-friendly config.py with detailed information on training in the future.
