### ISSUE TITLE
Why create a "global_part_neighbor" in the function "find_neighbor" in the skeleton.py?

### ISSUE THREAD

**Issue by crissallan** [DeepMotionEditing/deep-motion-editing#30]
Hi, 
I was recently reading the source code very carefully in order to understand the whole pipeline of your work.

I was kind of confused that why init a variable named "global_part_neighbor" in the  in the function "find_neighbor" in the line #373 of the models/skeleton.py?

Besides, why append a "edge_num" into those global_part_neighbor's list  in line #375?

Many thanks!

**Comment by PeizhuoLi** [comment]
Hi,

Line 373 is because we treat the global position channel as an "extra joint" and it shares the neighbor of the root joint, which is exactly global_part_nieghbor. 

For line 375, the "neighbor" relation is symmetric, so we add the extra joint (its index is edge_num, the last one) to the neighbor_list of its neighbors.

Hope this will help.

**Comment by crissallan** [comment]
> Hi,
> 
> Line 373 is because we treat the global position channel as an "extra joint" and it shares the neighbor of the root joint, which is exactly global_part_neighbor.
> 
> For line 375, the "neighbor" relation is symmetric, so we add the extra joint (its index is edge_num, the last one) to the neighbor_list of its neighbors.
> 
> Hope this will help.

Got it !Thank you so much for the answer!

**Comment by crissallan** [comment]
Hi, I recently found that there might be a mistake when calculating the neighbors of the "global_part_neighbor".

e.g. If you take read the .bvh file of "BigVegas", you can use debug mode of the IDE to found that the 22th element of the list which returned by the "find_neighbor" function is not the neighbors of the root joint(if you draw a graph of these 23 bones). It should be [0, 1, 4, 5, 8, 9], but got [0, 1, 2, 4, 5, 8, 9] instead.

I thinks it is because: at first, the index of the root joint is 0, but the "edges" eliminate the root joint, so when we obtain the neighbor_list  after the for loop in line #370 of the skeleton.py, the mistake occurs.

` global_part_neighbor = neighbor_list[0].copy()`

is not the neighbors of the root joint. I think it represents the neighbors of the "LeftUpLeg" of the "BigVegas"'s skeleton.(you could draw out the skeleton graph of the "BigVegas"'s 23 bones to verify it.)

**Comment by PeizhuoLi** [comment]
Thank you very mush for providing your findings! I think it's indeed a bug and we'll fix it later.

**Comment by fire** [comment]
Can you describe a way for fixing this? I can retrain my models.

**Comment by PeizhuoLi** [comment]
global_part_neighbor should be all the edges(armature) that contains joint with index zero. This condition should be used instead of a copy of neighbor_list[0].

**Comment by jdbodyfelt** [comment]
So if `neighbor_list = []` how can this be fixed?

**Comment by diversity-x** [comment]
global_part_neighbor = [] #新增的全局根节点
    #记录与根节点距离小于等于d的骨骼

    for edge in edges:
        if edge[0] == 0:
            for i,j in enumerate(edge_mat(edge[1])):
                if j < d:
                    global_part_neighbor.append(i)

**Comment by fire** [comment]
@PeizhuoLi I'm having trouble with neighbor_list = []

**Comment by PeizhuoLi** [comment]
Could you provide more details on how to reproduce this error? Thanks :)
