### ISSUE TITLE
The reason for represent rotation by quaternion instead of Euler angle.

### ISSUE THREAD

**Issue by crissallan** [DeepMotionEditing/deep-motion-editing#32]
Hi, sorry for bothering again,

May I ask the reason that why choose to use quaternion to represent the roration instead of the Euler angle? At first I thought that it is because if we don't know the implementation order of Euler angle, we might obtain wrong rotation, but  since we could know the order of Euler angle according to the .bvh file, why we still use the quaternion representation?

Many thanks!

**Comment by kfiraberman** [comment]
Great question.

Although Euler angles are used in the bvh format, this representation suffers from two main drawbacks: 
1. Ambiguity - The same rotation can be represented in various ways.
2. Discontinuity - Values with a large difference (like 0 and 359) may represent close rotation angles.

Hence, this representation is inconvenient for neural networks.

Quaternions representation may suffer from other issues but it’s much less severe. There are papers (like [this one](https://arxiv.org/abs/1812.07035)) that discuss these issues and try to propose alternative representations for rotations in neural networks. Empirically, to us, quaternions work well.

**Comment by crissallan** [comment]
Got it! Thanks for your explanation!
