### ISSUE TITLE
how to transfer json to bvh?

### ISSUE THREAD

**Issue by xinzi2018** [DeepMotionEditing/deep-motion-editing#34]

**Comment by HalfSummer11** [comment]
Hi, did you mean transferring the style from a 2D motion described by json to a 3D content motion in bvh format? 
To do so, please first make sure your json files are generated by OpenPose with options `--face`, `--hand` enabled. Below is an example:
`./build/examples/openpose/openpose.bin --video [your video path] --write_json [your json path] --display 0 --render_pose 0 --face --hand`

Then use the json path as the style source and run test.py.
`python style_transfer/test.py --content_src [your bvh] --style_src [your json path] --output_dir [your output path]`
 
Hope this would help.

**Comment by xinzi2018** [comment]
Thanks a lot!  in your way, i  test  style_Transfer  successfully!
But  i have another question ,in the retarget,   if i use my BVH,  the retarget/demo.sh will also not success.  (openpose not provide  the json to bvh,  so i use [VideoTo3dPoseAndBvh](https://github.com/HW140701/VideoTo3dPoseAndBvh)   to  transfer my own mp4 to BVH,but it only 17 landmarks)

**Comment by PeizhuoLi** [comment]
We are planning to release more details about using your own bvh soon. More details please check #31. Thank you.

**Comment by Qoo861207** [comment]
> Hi, did you mean transferring the style from a 2D motion described by json to a 3D content motion in bvh format? To do so, please first make sure your json files are generated by OpenPose with options `--face`, `--hand` enabled. Below is an example: `./build/examples/openpose/openpose.bin --video [your video path] --write_json [your json path] --display 0 --render_pose 0 --face --hand`
> 
> Then use the json path as the style source and run test.py. `python style_transfer/test.py --content_src [your bvh] --style_src [your json path] --output_dir [your output path]`
> 
> Hope this would help.

Can you explain how this code works? I don't know how to code at all
Is this used on cmd or python?
I use it on cmd in your way
`.python style_transfer\test.py --content_src test2.bvh --style_src D:\Newfo\openpose\examples\media\test1\test2.bvh --output_dir D:\Newfo\openpose\examples\media\test1`
As a result, the following problem occurred
`.python: can't open file'D:\\Newfo\\openpose\\bin\\style_transfer\\test.py': [Errno 2] No such file or directory`
