### ISSUE TITLE
test in style_transfer

### ISSUE THREAD

**Issue by xinzi2018** [DeepMotionEditing/deep-motion-editing#35]
In styleTransfer,when i use other BVHs,why cant run the style_transfer/demo.sh successfully?
is my skeleton in my BVH  is lack?  the skeleton must match it that you give?

**Comment by HalfSummer11** [comment]
Our style transfer framework deals with a fixed skeleton. To test our pretrained model, you need to first retarget your BVH to the skeleton described in style_transfer/global_info/rest.bvh. We'll provide more information on how to *train* the model with your own customized skeleton in the near future. Hope this would help.

**Comment by xinzi2018** [comment]
in style transfer ，when i want to change content BVH, how can i do? you say the skeleton should same as   style_transfer/global_info/rest.bvh, how can we get it  from our own avis?

**Comment by HalfSummer11** [comment]
Extracting 3D motions from 2D videos (3D motion reconstruction/pose estimation) is a fundamental research problem in computer vision. And it's beyond the scope of our style transfer framework. We only support direct usage of 2D videos as the *style input*.

**Comment by xinzi2018** [comment]
thanks a lot !
