### ISSUE TITLE
Why only send the position of root joint of each frame into the model as input?

### ISSUE THREAD

**Issue by crissallan** [DeepMotionEditing/deep-motion-editing#36]
Hi, 
I was kind of curious that why only send the position of root joint of each frame into the model as input?
I mean after parsing the .bvh file, we could get the positions of every joint at every frame. But we just use the root joint's position as input, is it because other joints' position info is redundant?

Mant thanks!

**Comment by PeizhuoLi** [comment]
As we only generate the rotation and global position, we find it's sufficient to use rotation as the network's input. However, we do use the position information in rec_loss and ee_loss to get more accurate result.

**Comment by crissallan** [comment]
> As we only generate the rotation and global position, we find it's sufficient to use rotation as the network's input. However, we do use the position information in rec_loss and ee_loss to get more accurate result.

Oh, it makes sense! To reconstruct the bvh file, we just need the position info of the root joint. I should have known that.
