### ISSUE TITLE
about skining

### ISSUE THREAD

**Issue by xinzi2018** [DeepMotionEditing/deep-motion-editing#40]
in the skining step ,i have some question. 
1. after we import the fbx what the mean about "Merge meshes - select all the parts and merge them (ctrl+J)"？
2. could you please give me more details about skining?

**Comment by kfiraberman** [comment]
1. In case that the mesh is consists of a few parts (hat, pants, skin, etc.), they should be merged into a single mesh with this operation.
2. Skinning is a broad topic that is beyond the scope of this repository. However, in case you have some particular questions, you can ask here.

**Comment by xinzi2018** [comment]
when i select all , then  ctrl+j   ,then blender2.7.9 will  say : no mesh data to join

**Comment by PeizhuoLi** [comment]
Maybe you can check our newly released auto skinning script.
