### ISSUE TITLE
I use my own data for retargeting, but the program will give an exception

### ISSUE THREAD

**Issue by wuxiaolianggit** [DeepMotionEditing/deep-motion-editing#42]
Traceback (most recent call last):
  File "eval_single_pair.py", line 104, in <module>
    main()
  File "eval_single_pair.py", line 92, in main
    new_motion = (new_motion - dataset.mean[i][j]) / dataset.var[i][j]
RuntimeError: The size of tensor a (99) must match the size of tensor b (91) at non-singleton dimension 1
Traceback (most recent call last):
  File "demo.py", line 46, in <module>
    example('Aj', 'BigVegas', '01.bvh', 'intra', './examples/intra_structure')
  File "demo.py", line 42, in example
    height)
  File "/home/wuxiaoliang/docker/newAPP/deep-motion-editing/retargeting/models/IK.py", line 57, in fix_foot_contact
    anim, name, ftime = BVH.load(input_file)
  File "../utils/BVH.py", line 58, in load
    f = open(filename, "r")
FileNotFoundError: [Errno 2] No such file or directory: './examples/intra_structure/result.bvh'

Hello, how can I solve this problem？@ @kfiraberman

**Comment by crissallan** [comment]
> Traceback (most recent call last):
> File "eval_single_pair.py", line 104, in
> main()
> File "eval_single_pair.py", line 92, in main
> new_motion = (new_motion - dataset.mean[i][j]) / dataset.var[i][j]
> RuntimeError: The size of tensor a (99) must match the size of tensor b (91) at non-singleton dimension 1
> Traceback (most recent call last):
> File "demo.py", line 46, in
> example('Aj', 'BigVegas', '01.bvh', 'intra', './examples/intra_structure')
> File "demo.py", line 42, in example
> height)
> File "/home/wuxiaoliang/docker/newAPP/deep-motion-editing/retargeting/models/IK.py", line 57, in fix_foot_contact
> anim, name, ftime = BVH.load(input_file)
> File "../utils/BVH.py", line 58, in load
> f = open(filename, "r")
> FileNotFoundError: [Errno 2] No such file or directory: './examples/intra_structure/result.bvh'
> 
> Hello, how can I solve this problem？@ @kfiraberman

create the directories  "./examples/intra_structure/" by yourself  before you run the program.

**Comment by wuxiaolianggit** [comment]
I've created the directory your way, but the same error still occurs @crissallan

**Comment by wuxiaolianggit** [comment]
RuntimeError: The size of tensor a (99) must match the size of tensor b (91) at non-singleton dimension 1，

This is the first exception

**Comment by crissallan** [comment]
> RuntimeError: The size of tensor a (99) must match the size of tensor b (91) at non-singleton dimension 1，
> 
> This is the first exception

Ah~ Since the tensor's shape doesn't match,  I think you should check whether  "01.bvh" is the mocap data of “Aj” or "BigVegas".
Because the shape of the motion tensor depends on the number of joints of the character. e.g. 91 = (23-1) * 4 + 3 because "Aj" and "BigVegas" both has 23 joints as its simplified skeleton.

So if tensor a's shape is 99, I would reckon that this bvh file might belongs to a character which has 24 joints.

**Comment by wuxiaolianggit** [comment]
OK, thank you very much for your reply,  

"Our approach is also quantitatively evaluated on a synthetic dataset that contains pairs of motions applied to different skeletons. To the best of our knowledge, our method is the first to perform retargeting between skeletons with differently sampled kinematic chains, without any paired examples. " , it is from "Skeleton-Aware Networks for Deep Motion Retargeting",

Is it required that the number of key points must be consistent？

**Comment by PeizhuoLi** [comment]
Our architecture requires a consistent topology between training character and test character. Thus, if you want to test with a new topology you will need to retrain the model with your own dataset.

**Comment by wuxiaolianggit** [comment]
thank you very much for your reply @PeizhuoLi

**Comment by fryegg** [comment]
Hi, I convert example.bvh file to csv file, and I found the number of joint was 31:
`Hips
Lhipjoint
leftupleg
leftleg
leftfoot
lefttoebase
rhipjoint
rightupleg
rightleg
rightfoot
righttoebase
lowerback
spine
spine1
neck
neck1
head
leftshoulder
leftarm
leftforearm
lefthand
leftfingerbase
lefthandindex1
lthumb
rightshoulder
rightarm
rightforearm
righthand
rightfingerbase
righthandindex1
rthumb
`
As I understand, the number of joints was 23. What difference between those?
