### ISSUE TITLE
ee_loss becomes "nan" type during training of the Retargeting model.

### ISSUE THREAD

**Issue by crissallan** [DeepMotionEditing/deep-motion-editing#44]
Hi there, I recently met a problem during training the retargeting model by myself. That is the "ee_loss" always became "nan" type during training,

Have you ever met this problem before? 

Many thansk!

**Comment by MikeXuQ** [comment]
Hi. It seems that I have met the same problem. Would you mind telling me how you solve this problem? Thanks a lot!

**Comment by crissallan** [comment]
> Hi. It seems that I have met the same problem. Would you mind telling me how you solve this problem? Thanks a lot!

Sorry, I haven't solve that problem yet. But the author has published and updated his training script,  I thought this problem should be solved. I'm not sure whether you pull the latest code from the repository?

**Comment by MikeXuQ** [comment]
> > Hi. It seems that I have met the same problem. Would you mind telling me how you solve this problem? Thanks a lot!
> 
> Sorry, I haven't solve that problem yet. But the author has published and updated his training script, I thought this problem should be solved. I'm not sure whether you pull the latest code from the repository?

Thanks for your reminding. But I have pull the latest code from the repository. Maybe there is something wrong when I made my custom dataset.

**Comment by shinshiner** [comment]
Same problem. Do you solve it? Is it caused by your custom dataset? @MikeXuQ
