### ISSUE TITLE
Basic concepts about "SkeletonConv" and "SkeletonUnpool".

### ISSUE THREAD

**Issue by crissallan** [DeepMotionEditing/deep-motion-editing#45]
Hi, after reading the implementation code of the skeleton.py. I got some questions which I'd like to disccuss with you.

1.Could I regard the "SkeletonConv" as a binary mask which created based on the neighboring list of each joint. If joint A is the neighbor of joint B, when convolve joint B, the binary mask on joint A is 1 else the mask is set to 0.

2.Does the "SkeletonUnpool" just duplicate the features of the pooled joint to increase the nodes of the skeleton graph? 

Many thanks!

**Comment by PeizhuoLi** [comment]
1. You are right. It is mathematically equivalent to use multiple conv1d module and a single conv1d with mask. The latter one is far more efficient in our experiments.

2. Yes. It works like some "duplicate unpooling layer".

Hope it helps.

**Comment by crissallan** [comment]
> 1. You are right. It is mathematically equivalent to use multiple conv1d modules and a single conv1d with mask. The latter one is far more efficient in our experiments.
> 2. Yes. It works like some "duplicate unpooling layer".
> 
> Hope it helps.

Thanks for the replying!
