### ISSUE TITLE
What is "xxx_virtual" joints produced by the function "build_joint_topology" in skeleton.py?

### ISSUE THREAD

**Issue by crissallan** [DeepMotionEditing/deep-motion-editing#46]
Hi there, I got a question about the function "build_joint_topology" in skeleton.py.

I could understand that this function is mapping the "edges" to "joints" thus we could write the info of "joints" into a .bvh file.

But why we need to add "xxx_vitual" joints to the skeleton?

And I was kind of confused about the role of the variable named "out_degree" defined in the line#295.

**Comment by crissallan** [comment]
> Hi there, I got a question about the function "build_joint_topology" in skeleton.py.
> 
> I could understand that this function is to map the "edges" in to "joints" thus we could write the info of "joints" into a .bvh file.
> 
> But why we need to add "xxx_vitual" joints to the skeleton?
> 
> And I was kind of confused about the role of the variable named "out_degree" defined in the line#295.

**Comment by PeizhuoLi** [comment]
BVH file only allows rigid child bones. But in this work we use edge representation and it's not rigid. So we create virtual bones with zero offsets from their parent to deal with this problem.

**Comment by crissallan** [comment]
> BVH file only allows rigid child bones. But in this work we use edge representation and it's not rigid. So we create virtual bones with zero offsets from their parent to deal with this problem.

Thanks a lot!
