### ISSUE TITLE
the style decoder take the offset as input, does it mean the offset to the parent or the last moment position

### ISSUE THREAD

**Issue by ucaswindlike** [DeepMotionEditing/deep-motion-editing#49]
the style decoder take the offset as input, does it mean the offset to the parent or the last moment position

**Comment by HalfSummer11** [comment]
Hi, in the style transfer project the style *encoder* takes the joint positions (relative to the root position) as input. (But the style transfer paper never mentioned "offset" or "style decoder". Which project are you referring to?)

**Comment by ucaswindlike** [comment]
Thank you, and I am so sorry to make a mistake in my question. I do mean the encode
