### ISSUE TITLE
the lambda in the option_parser.py is different from the paper

### ISSUE THREAD

**Issue by MikeXuQ** [DeepMotionEditing/deep-motion-editing#57]
Hi, when I read the source code, I find that the lambda set in the option_parser.py is different from the paper set, like the lambda_ee in the paper is 2 but is 100 in the option_parse.py. Have I missed something important?

**Comment by PeizhuoLi** [comment]
Sorry for our negligence. It should be 100 and we didn't fix it in the paper.

**Comment by MikeXuQ** [comment]
> Sorry for our negligence. It should be 100 and we didn't fix it in the paper.

Thanks for your reply! And I find that there is a extra rec_loss_global which seems to never appear in the paper. Would you mind telling me why using it here? And in the adv loss, the code use the pos as input, but the paper use the rotation as input. Is that better for using the pos as input for discriminator?

**Comment by PeizhuoLi** [comment]
We treat rec_loss_global as part of the rec_loss. It is an extra penalization over global position. It helps a lot with the global stability of output.

In adv_loss, the paper says both rotation and offset. We find using joint position is enough and joint position contains both (part of) rotation and offset information.

**Comment by MikeXuQ** [comment]
> We treat rec_loss_global as part of the rec_loss. It is an extra penalization over global position. It helps a lot with the global stability of output.
> 
> In adv_loss, the paper says both rotation and offset. We find using joint position is enough and joint position contains both (part of) rotation and offset information.

Do you mean that using joint position is better than use the rotation and offset?And why does the rec_loss_global use motion divided by height as input?

**Comment by PeizhuoLi** [comment]
We find that using position has same effect as literally using rotation + offset but easier to stabilize.

rec_loss_global is penalization over global position. Characters with different height have different scale of global position. Here dividing by height aims to normalize it.

**Comment by MikeXuQ** [comment]
But the motion is quaternion in the code. Can we use quaternion dividing by height as the representation of the global position?

**Comment by PeizhuoLi** [comment]
I'm afraid you misunderstood the code. Motion consists both joint rotation and global position part. The rec_loss_global is only applied on global position part.

**Comment by MikeXuQ** [comment]
Thanks! I got it!
