### ISSUE TITLE
how can we test our own bvh in the retargeting?

### ISSUE THREAD

**Issue by xinzi2018** [DeepMotionEditing/deep-motion-editing#60]
my bvh is generate from alphapose->bvh. 
i know my bvh'skeletons  are different ,so how can i get my bvh to your bvh'skeletons?

**Comment by xinzi2018** [comment]
i need to change retargeting/datasets/bvh_parser.py ,then to retrain the retarget model in my own skeletons?

**Comment by PeizhuoLi** [comment]
If the skeleton's topology is different, retraining is necessary.
