### ISSUE TITLE
About the mean and var of each character?

### ISSUE THREAD

**Issue by crissallan** [DeepMotionEditing/deep-motion-editing#61]
Hi, 

I have a question about the mean and var located  in the ./retargeting/datasets/Mixamo/mean_var.

I'd like to know the mean and var of each character's motion data are just calculated based on the test data or they are calculated based on the whole dataset?

If it is the whole dataset, how many data did you use to calculate the mean and var?

Many thanks!

**Comment by PeizhuoLi** [comment]
For test data we used the whole Mixamo dataset to calculate the mean and var. Roughly 490000 frames @60fps. Perhaps the whole dataset is not necessary.
