### ISSUE TITLE
As seen in the demo (same animation is necessary to have the character as well（Goblin_m', 'Goblin_m）or（BigVegas', 'BigVegas）? 

### ISSUE THREAD

**Issue by wuxiaolianggit** [DeepMotionEditing/deep-motion-editing#62]
As seen in the demo (same animation bvh file exists to both input and destination character) with intra, is it necessary to have the same animation's bvh file for the destination character as well（Goblin_m', 'Goblin_m）or（BigVegas', 'BigVegas）?  

how to slove the problem？ @ @kfiraberman

**Comment by PeizhuoLi** [comment]
See #59.
