### ISSUE TITLE
about  architecture.py->def backward_d(self)  :  in retargeting

### ISSUE THREAD

**Issue by xinzi2018** [DeepMotionEditing/deep-motion-editing#64]
i want to retain the retarget model use my own dataset(eg：cmu dataset).
when i use cmu dataset ,i find split_joint.py cant split the dataset into '***_m'.  so my len(characters)==1 in the retargeting/datasets/__init__.py
then  when the code run in architecture.py->def backward_d(self)->fake = self.fake_pools[i].query(self.fake_pos[2 - i])： i will have a error:IndexError: list index out of range
so what the mean about  "self.fake_pos[2 - i]"?

**Comment by PeizhuoLi** [comment]
The length of self.fake_pose is 4. It stores the retargeting result as the following order: group A -> group A, A->B, B->A, B->B. 2 - i means we only take A->B and B->A for adversarial loss.

**Comment by xinzi2018** [comment]
thanks a  lot !!!
