### ISSUE TITLE
May i ask a question?

### ISSUE THREAD

**Issue by ronghui19** [DeepMotionEditing/deep-motion-editing#67]
What is the difference between motion retargeting and motion style transfer?

**Comment by kfiraberman** [comment]
In general, you can think of an animation as a combination of "motion" and "skeleton", where the "motion" part can be decomposed into "content" and "style".

Given two animations A and B,
*Motion retargeting* = transfer the motion of A so to the skeleton of B (or vice versa),
*Motion style transfer* = generate a new motion that has the motion content of A and the motion style of B (in this case we assume that A and B have the same skeleton).
