### ISSUE TITLE
Dose the "T-pose" of a character only depend on the "static offset" of the bvh file?

### ISSUE THREAD

**Issue by crissallan** [DeepMotionEditing/deep-motion-editing#68]
Hi Peizhuo,

I'd like know that dose the "T-pose" of a character only depend on the "static offset" of the bvh file?

Since I had 2 characters with different T-pose(I saw the difference in the Blender). And the retargeting results is wierd. 

So I might need to re-edit the offset info of the bvh file.

Many thanks

**Comment by kfiraberman** [comment]
That's correct. The "T-pose" of a character is the static offsets within the bvh file.

**Comment by crissallan** [comment]
> That's correct. The "T-pose" of a character is the static offsets within the bvh file.

Thanks a lot!

**Comment by crissallan** [comment]
Hi,
I'd also like to make sure that is the order of the OFFSET in the bvh file is "X, Z, Y" instead of "X,Y,Z". 
Because when I change the second number of a joint's OFFSET info, and I found that the difference appears on the "Z" axis in Blender.

**Comment by PeizhuoLi** [comment]
This is the "problem" of Blender. Blender uses Z axis as "up" direction while bvh uses Y axis. When you import a bvh to Blender, a coordinate conversion will be automatically performed.
