### ISSUE TITLE
alpha function and lerp function

### ISSUE THREAD

**Issue by MikeXuQ** [DeepMotionEditing/deep-motion-editing#69]
Hi, would you mind telling me what does the alpha function and lerp function in IK.py mean?

**Comment by HalfSummer11** [comment]
Hi, to clean up footskate artifacts we followed the method from [Footskate Cleanup for Motion Capture Editing](https://research.cs.wisc.edu/graphics/Gallery/kovar.vol/Cleanup/#:~:text=Footskate%20Cleanup%20for%20Motion%20Capture%20Editing%20Lucas%20Kovar%2C,to%20satisfy%20the%20particular%20demands%20of%20the%20animation). Here alpha(t) is a smooth blending weight function, and lerp(a, l, r) produces a linear interpolation between l, r. More details can be found in Section 4.2 of the paper. 
Hope this would help.

**Comment by MikeXuQ** [comment]
> Hi, to clean up footskate artifacts we followed the method from [Footskate Cleanup for Motion Capture Editing](https://research.cs.wisc.edu/graphics/Gallery/kovar.vol/Cleanup/#:~:text=Footskate%20Cleanup%20for%20Motion%20Capture%20Editing%20Lucas%20Kovar%2C,to%20satisfy%20the%20particular%20demands%20of%20the%20animation). Here alpha(t) is a smooth blending weight function, and lerp(a, l, r) produces a linear interpolation between l, r. More details can be found in Section 4.2 of the paper.
> Hope this would help.

Thanks a lot!
