### ISSUE TITLE
Manual Skinning

### ISSUE THREAD

**Issue by chaserat** [DeepMotionEditing/deep-motion-editing#70]
When I try to do skinning as supposed, I find the number of "mousey" is different with that in the "result.bvh" in "../retargeting/examples/crosss_tructure". I failed to merge the "result.bvh" with the "mousey" model. 
In "result.bvh", I found the "LeftUpLeg_virtual"  Joint is undefined in the "mousey" model. What's the "*_virtual" Joints supposed in "mousey" model? Are they  important?

**Comment by PeizhuoLi** [comment]
If you are following our instruction for manual skinning, I think the *_virtual joints shouldn't cause any problem. In bvh files, child bones for a specific joint are relative rigid, see [here](https://github.com/DeepMotionEditing/deep-motion-editing/issues/33#issuecomment-645157707) and #46.

**Comment by chaserat** [comment]
In the way of config the enviro ( blender 2.76), I process the "mousey" model with the generated "result.bvh" in "../retargeting/examples/crosss_tructure".
The result comes out strange like this: 
![image](https://user-images.githubusercontent.com/30485904/87553718-d74a4280-c6e5-11ea-9e1e-82ef3fd79ae0.png)

as the error in terminal is：

Did the bvh file go wrong or my

**Comment by PeizhuoLi** [comment]
It looks like the skeleton in rest pose is not aligned with mesh to me. Also it could be a problem caused by blender version. We've only tested on blender >= 2.8.

**Comment by chaserat** [comment]
Thank you! The blender version is the right solution.
In the motion, the arms of "mousey" run into the head area. Does the origin bvh show the same phenomenon in the origin model?
