### ISSUE TITLE
about Automatic Skinning---> blender -P blender_rendering/skinning.py

### ISSUE THREAD

**Issue by xinzi2018** [DeepMotionEditing/deep-motion-editing#72]
blender2.83
当我运行 "blender -P blender_rendering/skinning.py -- --bvh_file [bvh file path] --fbx_file [fbx file path]" 这个命令之后 发现 ，动漫人物的动作都是对的 皮肤也是对的  但是人物的坐标轴转动了，显示的时候时躺着的？

**Comment by PeizhuoLi** [comment]
这个问题我没有遇到，但应该可以通过在blender中给skeleton设置一些旋转解决。

**Comment by xinzi2018** [comment]
我发现下载下来的Mousey.fbx文件用blender导入显示的时候，它便是躺着的（脸朝着Z轴），是我下载方式错误嘛？我是直接使用你给的下载Mousey的链接(format=fbx,pose=T-pose)

**Comment by xinzi2018** [comment]
我将文件拖到本地之后，显示不会错乱了。
我还有一个问题要请教的： 就是我在skinning.py的代码最后加上“bpy.ops.export_scene.fbx(filepath=args.save_path) ”保存成fbx,但拖到本地查看的时候发现在Collection 中总是还存在Armature,以至于在使用win10自带的3D查看器无法预览。（如果在本地手动将Armature删掉再保存成fbx,便可以再3D查看器中能预览）

**Comment by xinzi2018** [comment]
尝试了下用代码去进行删除Armature,虽然能删除成功，但是Mousey的动作总是出错，是不是我代码删除的方式错误？
c = bpy.data.collections['Collection']
bpy.data.objects.remove(c.objects['Armature'])

**Comment by PeizhuoLi** [comment]
这个脚本的功能仅限于在blender中实现自动skinning，导出为fbx文件可能会出现问题。在原始的fbx文件中，自带的armature是mesh的parent object, 但在skinning脚本中方便起见，没有更改层级关系。这可能是一个问题。
