### ISSUE TITLE
Want to know the Structure of Keypoints

### ISSUE THREAD

**Issue by fryegg** [DeepMotionEditing/deep-motion-editing#76]
I converted the example bvh file called "example.bvh" into csv file. The number of keypoints was 31. (So the number of column was 3 x 31 + 1 (time or frame num column) = 94).  I want to know the name of keypoints such as SMPL or CMU. 
List of keypoints what I found :
`Hips
Lhipjoint
leftupleg
leftleg
leftfoot
lefttoebase
rhipjoint
rightupleg
rightleg
rightfoot
righttoebase
lowerback
spine
spine1
neck
neck1
head
leftshoulder
leftarm
leftforearm
lefthand
leftfingerbase
lefthandindex1
lthumb
rightshoulder
rightarm
rightforearm
righthand
rightfingerbase
righthandindex1
rthumb`

**Comment by PeizhuoLi** [comment]
The name of keypoints is listed in the bvh file. You can open the bvh file with a text editor.
