### ISSUE TITLE
how about 2d  skeleton to video rendering?

### ISSUE THREAD

**Issue by ronghui19** [DeepMotionEditing/deep-motion-editing#84]
I noticed author for this project is as same  as the author for 2d motion retargeting. I have a question. How to render skeleton to video so  i can actually see people doing what we want them to do? Where can i find out the script?

**Comment by kfiraberman** [comment]
Hi, this question is not directly related to this repository. We do not provide such a script for re-rendering videos. 
You can refer to this [issue](https://github.com/ChrisWu1997/2D-Motion-Retargeting/issues/14#issuecomment-526292854) to read about some related work. I recommend looking online for implementation of [everybody dance now](https://carolineec.github.io/everybody_dance_now/), which is probably what you are looking for.
