### ISSUE TITLE
Questions about the network structure

### ISSUE THREAD

**Issue by catherineytw** [DeepMotionEditing/deep-motion-editing#85]
hi, I was carefully reading the code and paper in the past few days, and had to say that it was really amazing! 

but when I dug into the details and was confused about the implementation of the Encoder structure.

In the paper, the network has two layers, each of which has 3 operations and comes in the sequence of { skeletonConv, ReLu, and pooling}, but in the code, the order of the skeleton pooling and relu are inverted. Below is the module list I printed out to show the inconsistency, and was wondering which one was correct?

Many thanks!

![image](https://user-images.githubusercontent.com/13126608/89760441-f7bbc000-db1e-11ea-95f0-4bf781fb9ceb.png)

The module list of encoder I printed:
Encoder:
ModuleList(
  (0): Sequential(
    (0): SkeletonConv(
      (offset_enc): SkeletonLinear()
    )
    (1): SkeletonPool()
    (2): LeakyReLU(negative_slope=0.2)
  )
  (1): Sequential(
    (0): SkeletonConv(
      (offset_enc): SkeletonLinear()
    )
    (1): SkeletonPool()
    (2): LeakyReLU(negative_slope=0.2)
  )
)

**Comment by PeizhuoLi** [comment]
Hi, thanks for your interest in this project. 
You are right about the code. We made a mistake in the paper. The correct order is Conv, Pool, LeakyReLU.

**Comment by catherineytw** [comment]
Many thanks. 


Sent from Yahoo Mail for iPhone


On Tuesday, August 11, 2020, 22:47, Peizhuo <notifications@github.com> wrote:




Hi, thanks for your interest in this project.
You are right about the code. We made a mistake in the paper. The correct order is Conv, Pool, LeakyReLU.
