### ISSUE TITLE
a question for skeleton denoising

### ISSUE THREAD

**Issue by guker** [DeepMotionEditing/deep-motion-editing#87]
Now, I generate 3D pose coordinates  using 3D pose estimation algorithm for a video, but this coordinate have some jitter,  can your algorithm use for skeleton denosing?

**Comment by kfiraberman** [comment]
Our existing auto-encoder is applied to joint rotations, so it is not straightforward.
Theoretically speaking you can use our skeleton-aware operators with 3D joints positions, but it requires some (minor) modifications of the existing code and re-training of the network to convert noisy 3D position to clean ones (so you should also have clean data for training).
