### ISSUE TITLE
a question for the output of static encoder

### ISSUE THREAD

**Issue by bo-jia** [DeepMotionEditing/deep-motion-editing#89]
First, thanks for sharing the amazing project. 
I found the outputs of the static encoder were not used in the forward of encoder-decoder. The output features, the offset, were set in the SkeletonConv, but not concatenated with the input in the forward. I was confused about that. It seemed the static-encoder didn’t work.

**Comment by PeizhuoLi** [comment]
Hi, thanks for your interest in our project.

We use some trick in implementation considering efficiency so it's not exactly the same as the paper describes. Repeating and concating then applying convolution is actually equivalent to do a separate linear transformation on deep offset representation then add the result to the convolution result. We use the latter one in our implementation.
