### ISSUE TITLE
Wanna train on another dataset.

### ISSUE THREAD

**Issue by PKUFlyingPig** [DeepMotionEditing/deep-motion-editing#91]
If I want to train the model on another dataset, what data should I provide? Both the original pose bvh and target pose bvh? If so, should they be paired?  i.e. If I want to transform poses from A to B, should the data in A and B have the same action or not ?

**Comment by kfiraberman** [comment]
Yes, you need two sets of bvh files, where each set contains the same skeletal structure (joint adjacencies, but it is not necessary to have the same offsets). The sets doesn't have to be paired, but if the motions in the two sets are somewhat similar it definitely helps to get better results.
