### ISSUE TITLE
How did you experiment Retargeting to asymmetric characters?

### ISSUE THREAD

**Issue by whitealex95** [DeepMotionEditing/deep-motion-editing#94]
According to the Fig.12 in your paper(https://deepmotionediting.github.io/papers/skeleton-aware-camera-ready.pdf),
you tested motion retargeting on characters with asymmetric armature. However, according to your method, you need a set of  character motions for motion retargeting. Did you manually create a set of motions for characters with asymmetric armature? or did you do try something else?

**Comment by kfiraberman** [comment]
Since the character is unique in this case, the set contains a single character (with many motions).

**Comment by whitealex95** [comment]
Thanks!
