### ISSUE TITLE
运行test.py出了一些错误

### ISSUE THREAD

**Issue by zhangcheng828** [DeepMotionEditing/deep-motion-editing#96]
你好，我在windows系统成功运行了demo.sh，但是运行test.py出现了错误，能告诉我是什么原因导致的吗？谢谢
![QQ截图20201019123506](https://user-images.githubusercontent.com/72736693/96402049-8b88c700-1207-11eb-847b-ba123dc1da9d.png)

**Comment by PeizhuoLi** [comment]
你好，我们的代码仅在Linux和macOS平台上测试过，Windows上可能有不完善的地方。另外，根据你提供的输出结果，应该是只出现了一个Warning，test已经正确执行并输出了和论文中一致的测试结果。希望这个回答有帮助。

**Comment by zhangcheng828** [comment]
多谢回答，意思是下面的collecting test error 和 Intra-retargeting error不影响实验结果吗？

**Comment by PeizhuoLi** [comment]
是的。下面的collecting error意思是在收集我们的结果和ground truth之间的误差，并不是运行错误。

**Comment by zhangcheng828** [comment]
哦哦，我还以为出错了，不好意思
