### ISSUE TITLE
Motion Style Transfer could not be generated xia.npz and bfa.npz

### ISSUE THREAD

**Issue by miss-rain** [DeepMotionEditing/deep-motion-editing#98]
Motion Style Transfer
Extract the .zip files into style_transfer/data.Pre-process data for training:
cd style_transfer/data_proc
sh gen_dataset.sh

issues:
the command was not effective after running, and it could not be generated xia.npz and bfa.npz

**Comment by HalfSummer11** [comment]
Did you uncomment the relevant lines in gen_dataset.sh? Currently all lines are commented out there.

**Comment by miss-rain** [comment]
thanks very much, it can work,thank you .
